apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    cluster2.local:53 {
        rewrite name substring cluster2.local cluster.local
        forward . 172.18.0.201 {
            expire 10s
            policy round_robin
        }
        cache 10
    }
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        rewrite name substring cluster1.local cluster.local
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        cache 30
        loop
        reload
        loadbalance
    }
